name: CI Java

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Check Google codingstyle
        run: cd buildtools/ginga-java && ./mvnw spotless:check

      - name: Build with Maven wrapper
        run: cd buildtools/ginga-java && ./mvnw package -B
